// ArmSight Service Worker — Offline Cache
// Bump this version string any time you deploy a new build
const CACHE = 'armsight-v136';
// ── CHANGELOG — append ONE line per version bump; never rewrite past entries ──
// v49  pickoffs removed from prediction model, shown as their own card; Events dead-code fix
// v50  new prediction model (within-AB sequencing, command decay, batter memory, count/order leans, bunt); velocity removed
// v51  tab restructure: Games, Chart, Pitching Tendencies, Baserunning, Hitting (soon), Library (completed games)
// v52  Pitching Tendencies analyzer: multi-select pitcher chips + This Game / All Games scope toggle
// v53  PT sub-tabs (Analyzer default + Scouting Report); SB/CS/WP/PB removed from analyzer Result filter; Pickoffs non-collapsible; Outs filter added
// v54  Baserunning Events card rebuilt: non-collapsible, breakdown by preceding-pitch type + count + outs
// v55  SB/CS/WP/PB/PK-E store destination base(s); per-runner + "All runners advance" buttons; Baserunning event/base filters; By Base row
// v56  Baserunning Events cards show "By Pitch" only; Count/Outs/Base/Event are multi-select filters keyed off the preceding pitch
// v57  Pitcher Read panel on Chart tab (1B: move/step/hand; 2B: look count); 2B Look Count + 1B Tendencies cards on Baserunning tab
// v58  1B step extended to 5+
// v59  2B move type (Inside/Spin) added to Pitcher Read panel and 2B report card
// v60  Baserunning read cards use scopedGames not rawPool — fixes missing data on Baserunning tab
// v61  Baserunning tab empty state + data counter
// v62  brRead stale closure fixed (dep array); mkBR helper; all logPKO/logPK/logPKE/logEvent attach brRead
// v63  brPool no longer excludes EVENTS — pickoff reads now appear in Baserunning tab cards
// v64  Firebase helper (getFB) hardened — typeof guard + existing-app fallback; removes spurious init warning
// v65  Pitcher Reads (2B + 1B) grouped under one collapsible block on Baserunning tab; debug data line removed
// v66  Firebase SDK added to offline precache — sync queues offline and flushes on reconnect even on a cold offline start
// v67  Scout Notes — free-text notes per opponent stored at app level; quick-add 📝 on Chart tab; full add/edit/delete on Scouting Report sub-tab
// v68  Hitting tab: QAB+HH tracking with 4s auto-close tag panel, team+individual stats, hard hit heat map, Settings toggle
// v69  HH now counts as QAB; hhPitches no longer requires location; heat map shows guidance when no zones logged
// v70  Heat map renders proper zone grid split by LHB/RHB; BatterZone removed from Hitting
// v71  Hitting rebuilt as filtered analyzer — QAB/HH by PA/AB, filters: hitter/count/outs/runners/QAB type
// v72  Hitting: pitch type filter added; avg displays as .333 format; HH calc fixed
// v73  buildAtBats: a new AB starts after a result pitch — fixes AB double-counting for the same batter
// v74  Hitting: Hard Hit Avg denominator fixed to balls in play (was official AB, could exceed 1.000)
// v75  Hitting: removed "in play" label under Hard Hit Avg
// v76  Unified scope cascade (Hand -> Teams -> Games by date -> Pitchers) — shared module; wired into Hitting first
// v77  Scope cascade rolled into Pitching Tendencies + Baserunning; hand now reliever-aware across all three tabs
// v78  Pregame scouting: per-game pregame flag (scouted vs a different opponent) feeds primer + pitch tendencies + pickoff reads; Tier-2 fence keeps it out of outcome rates, the result filter, baserunning events/pickoff success and the Hitting tab; Live/Pregame source chip on the scope cascade
// v79  New Game: pregame toggle replaced with a clear two-option Game Type selector (Live game | Pregame scout), active option highlighted — fixes the confusing single button that showed current state
// v80  Retroactive Hitting editor (HittingLog) — tag QAB/hard-hit per at-bat after the game from the Chart tab; per-at-bat hitter override so pinch hitters attribute to themselves (buildAtBats resolves pitch.hitter || lineup slot; includeUnnamed for the editor); live panel unchanged
// v81  Live tag panel now prompts on out/hit/FC/GDP/ROE only (added FC); hit & ROE show Hard Hit only since they auto-log as QAB, while out/FC/GDP show the full HH+QAB tag set — detailed situational tagging stays in the post-game HittingLog editor
// v82  Live tag panel reworked: fixed outs not prompting (out logs go/fo/po/lo — all restored to trigger); removed 4s auto-close (taps save immediately, Done or next pitch dismisses); panel now renders under the result entry; live choices reduced to Hard Hit + a generic QAB flag (hit/ROE show Hard Hit only), with specific QAB types (sac fly/bunt/adv runner/RBI) chosen post-game in HittingLog, which gains a QAB chip
// v83  Hitting tab rebuilt as an MLB/ESPN-style sortable table: rows = hitters under the scope bar, presorted QAB high-to-low, always-on Hitter/PA/QAB/Hit(BA)/HH columns, team row pinned at bottom. Split selector (QAB Type totals / Pitch Type / Count A-E-B / Outs / Runners) swaps the trailing columns; tap any header to sort. Hard Hit is its own avg and never double-counts toward QAB; QAB-type totals overlap by design. Team hard-hit heat map under the table; tap a hitter to open their own heat map. Old filter-chip UI replaced.
// v84  Hitting table: removed the Hit (batting avg) column (teams already track BA; avoids a credibility-risking near-miss); added hover tooltips on QAB/HH and the QAB-type headers plus a tappable Key panel (mobile-friendly); added a Hits by pitch type table (rows 1B/2B/3B/HR x Fastball/Breaking/Offspeed counts, scope-aware) so coaches can see which pitch families produce hits
// v85  Hard Hit avg now computed over at-bats (not balls in play): excludes walks/HBP/intentional walks and sac bunts, but counts sac flies as an at-bat (numerator also gated so a hard-hit sac bunt can't exceed 1.0). Removed 'Men on' from the Runners options (Empty / RISP only)
// v86  Hitting tab: dropdowns are now situational FILTERS (Pitch Type / Count / Outs / Runners) that apply to HH avg + the new per-hitter hit-type columns (1B/2B/3B/HR) and the team heat map + hits-by-pitch card — QAB and PA stay overall, never filtered. QAB-type breakdown (On base/6+/4P-2K/Move-RBI/Sac/QAB?) moved into the per-hitter popup alongside the heat map. Columns: Hitter/PA/QAB/HH/1B/2B/3B/HR.
// v87  Hitting tab: heat maps now show HARD-HIT AVG BY ZONE (hard hits / at-bats ending in each zone) colored attack(.400+ red)/mixed(amber)/lay-off(<.250 blue), with n shown and samples <2 muted — for attack/lay-off coaching. Dropped the hit-type columns (table is now Hitter/PA/QAB/HH) and removed the Hits-by-pitch table. Per-hitter popup gained its own Pitch/Count/Outs/Runners filters (seeded from the table's) driving its zone map. Team + individual maps both filter-driven; QAB/PA still overall.
// v88  Manual scoreboard header at top of ChartGame: team scores with +/- and a Top/Bottom half toggle (both persist on the game object); inning + out lights mirror the live count and stay editable in the controls below. GameChanger feed/auto-parse engine intentionally NOT included (no public API to poll).
// v89  Scoreboard header restyled into two highlighted team cards ordered AWAY first / HOME second, my team accented in gold, with a MINE: HOME/AWAY flip toggle (persists as game.homeAway). NewG gains a persistent 'Your team' field that defaults from the most recent game's team and flows through create() to game.team.
// v90  Scoreboard cleanup: removed the literal '. MINE' tag (the gold card already marks my team) and made the MINE: HOME/AWAY flip toggle gold so it reads as the switch. Fixed a display bug in the post-game Hitting editor where a literal escaped middle-dot rendered as stray characters after the result; now shows a real separator.
// v91  Scoreboard home/away toggle now just reads HOME / AWAY (dropped the 'MINE:' prefix).
// v92  Scoreboard inning toggle now steps through half-innings (Top->Bottom->next inning's Top) instead of only flipping the half, capped at Bottom 25; advances live inning via setInning. Manual inning +/- controls below unchanged for going back.
// v93  (dummy-site trial) Two additive features: (1) Chart tab gets a read-only 'location heat map' toggle showing where the current pitcher throws in the live count/outs/runners situation (across batters, aggregated from all that pitcher's games) - does not affect charting or any other structure. (2) Games screen gets an 'Import CSV' button (minimal pitch-level CSV: headers type/location/result, optional balls/strikes/outs/batSide/inning/pitcher) that creates a new game from the rows.
// v94  Chart location heat map reworked: removed the exact count/outs/runners filter (it left it almost always empty) so it now accumulates all of the pitcher's located pitches as you chart; and instead of a blue frequency shade, each zone shows the pitch count plus a pitch-type-mix bar (fastball/breaking/offspeed) with a legend, so coaches can read which pitches go to which zones.
// v95  (dummy-site) Chart layout pass 1: Prediction collapses to a compact always-visible strip (top pick + %, confidence badge) with a Details toggle for the full bars - so it no longer splits the zone->type->result entry flow and cuts the mid-pitch scrolling. Chart page also capped to maxWidth 1040 and centered so it reads cleanly on laptop/iPad instead of stretching. Prediction engine itself unchanged. Full two-column tablet/desktop split is the next pass.
// v96  (dummy-site) Chart layout pass 2 - responsive two-column. At >=880px wide (iPad landscape, laptops, desktop) the chart splits into a left entry cockpit (controls/zone -> compact prediction -> pitch type -> result) and a right intel column (recent log, live mix, scouting); below 880px it stacks back to the single phone column unchanged. Full-width top (scoreboard, status, heat-map toggle) spans both. Width-driven via an isWide resize listener; page still capped at maxWidth 1040 and centered. No charting logic touched - pure reparent.
// v97  (dummy-site) Chart layout pass 3 - relocated the Prediction to a sticky strip pinned at the top of the chart (full width, above the two columns), out of the entry flow. This also auto-groups the cockpit (controls/zone -> pitch type -> result are now contiguous). Compact-by-default with Details toggle preserved; prediction engine untouched. Matches the mockup: sticky prediction on top, grouped cockpit, two-column intel on wide screens.
// v98  (dummy-site) Chart layout pass 4 (final mockup piece): on phones the right-column intel (recent pitches, live mix, scouting) now collapses behind a single 'More' toggle, collapsed by default, so the cockpit sits higher; on wide screens (>=880px) it stays always-open in the right column. Completes the mockup: sticky prediction on top, grouped cockpit, collapsible extras on phone, two-column on wide.
// v99  (dummy-site) Added a manual 'Split view' toggle on phones: forces the two-column iPad/desktop layout (cockpit left, intel right) even below 880px, via a forceWide override (wide = isWide || forceWide) driving the grid, the More toggle, and the extras wrap. Lets a coach choose the side-by-side dense layout on a phone instead of scrolling. Auto width behavior unchanged on wide screens.
// v100  (dummy-site) Phone view reworked away from the split layout: removed the standalone 'location heat map' toggle; added a 4-button row (Heat Map / Recent Pitches / Live Mix / Scouting) that each open an X-able popup with that info. Content (heat map, recent, live mix, scouting) defined once as reusable pieces and shared by both the popups and the bottom 'More' collapse (which now also includes the heat map). Prediction card tightened (padding 8x12). Wide-screen two-column layout and prediction engine unchanged.
// v101  (dummy-site) Location input: added a 'Low' ball zone above 'Dirt' (a low pitch that's a ball but didn't bounce), so every zone grid is now 6 rows; renamed the side ball labels 'Way In/Way Away' to 'Off In/Off Away'. Prediction: new dirt-spike read — if a pitcher has buried the same pitch type in the dirt 3+ times, a tip surfaces ('Look for the X in the dirt — he's spiked it Nx').
// v102  (dummy-site) Prediction model gains two graceful, additive signals. (1) Eye-level: when the prior pitch was an UP fastball taken for a ball, breaking/offspeed get a lean and fastball a small fade for the next pitch — gated on the prior pitch having a location, so skipping the zone just turns this term off (weight stays with count). (2) Score leverage: pitcher's-team margin (scoreOpp-scoreUs) nudges pitch family — a comfortable lead (>=4) leans fastball/attack, trailing (<=-3) leans breaking/offspeed; neutral at a 0 margin, so an untouched scoreboard has no effect. Both are small multipliers layered after the existing count/sequence/profile scoring.
// v103  (dummy-site) Location now feeds prediction generally. Tier 1 — sequencing is location-aware: the engine learns 'after pitch X to a spot (up/down/in/away) with result R, what came next?' for THIS pitcher, used as the richest tier of the sequence cascade (falls back to type+result, then type, then count when a located sample is thin). This replaces the hardcoded up-fastball rule with a learned version; the heuristic stays only as a no-data fallback. Tier 2 — effectiveness lean: pitch types missing bats above the pitcher's own average whiff rate get a small boost (capped +20%). Both gated on located samples, so skipping zones just falls back to the prior model.
// v104  (dummy-site) Location-aware sequencing now prioritizes the in/away axis over height: a pitch buckets as in/away first (the more prevalent sequencing axis in most pitchers' mixes) and only falls back to up/down for middle-of-plate pitches. The up-fastball chase read still fires via the separate two-strike heuristic, so that case isn't lost.
// v105  (dummy-site) Hitting tab gains plate-discipline columns: Whiff% (swinging strikes / swings), Chase% (swings at out-of-zone pitches / out-of-zone pitches seen — needs locations), and Take% (pitches taken / pitches seen). Computed per pitch, sortable, and they reflect the Pitch/Count/Outs/Runners filters (PA and QAB stay overall). Shared per-pitch classifier added so the same engine can later drive the per-hitter heat maps and the pitcher-side (induced) version. Team row totals included.
// v106  (dummy-site) Per-hitter popup now has a metric selector (Hard-hit / Whiff / Chase / Take); each draws a by-zone heat map split RHB/LHB, driven by the popup's own Pitch/Count/Outs/Runners filters. Whiff% per zone = swing-and-miss/swings, Chase% shows on out-of-zone cells only (swings/seen there), Take% = takes/seen; brighter = higher, n shown, <3 muted. Also removed the PA column from the Hitting table (available on team-stat sites).
// v107  (dummy-site) Pitching Tendencies analyzer gains an 'induced' Plate Discipline card (same engine, grouped by the scoped pitcher): big Whiff/Chase/Take readouts (tap to switch), its own Pitch/Count/Outs/Runners dropdown filters, and a by-zone heat map vs RHB/LHB for the selected metric. Whiff = swing-and-miss/swings he gets, Chase = swings/seen on out-of-zone pitches he draws, Take = takes/seen he allows. Gated to the zones (Pro) tier like the existing heat map.
// v108  Bug-fix pass: buildAtBats stops splitting ABs on mid-AB K/Kc (fixes inflated PA / deflated QAB+HH); resume state (deriveStateFromGame) handles go/fo/po/lo/gdp/ibb; cloud merge keeps scoutingNotes/prefs and prefers updatedAt (now stamped on saves) over pitch count; prediction memo keys on curP; getLineupHand precedence fix; storage-quota save failures now alert + storage.persist() requested; CSV import validates/normalizes result+location and reports skipped rows; SW: no skipWaiting at install (update banner now functional), app shell cached via addAll, runtime cache limited to app origin + known CDN hosts
// v109  Bunt + Sac Fly charting: a 'Bunt' arm-toggle stamps bunt:true on the next result (any of hit/ROE/out/GO/FC/PO/foul/K/ball) — a two-strike foul bunt auto-converts to a K, and a bunted out with runners on auto-tags sacBunt (QAB + hard-hit exclusion ride the existing tags pipeline), auto-advances every runner one base, and the tag panel offers RBI (squeeze) / moved-runner; new 'Sac Fly' button (enabled with R3) logs FO + sacFly + RBI, scores the runner from third, panel offers Hard Hit; resume state mirrors both sac movements; plate-discipline engine now excludes bunt pitches and ambiguous wp/pb results from Whiff/Chase/Take; CSV import accepts an optional bunt column (1/y/yes/true/x); induced Plate-Discipline count filter relabeled 'Hitter Ahead/Behind'
// v110  Server-side license validation scaffold: new serverValidateKey -> POST {worker}/validate (endpoint added to armsight-worker.js, checks the issued-key sheet); unlock screen rejects keys the server affirmatively reports as not issued, App rechecks every 12h with server-authoritative tier — offline/unreachable NEVER locks (grace), and LIC_API="" ships it dormant (pre-v110 behavior) until the worker URL is pasted in; Import CSV button removed from the Games list for now (importCSV/parsePitchCSV kept intact — re-enable by restoring the onImport prop)
// v111  Bunts now self-classify for the QAB chart with zero required taps: bunt hit/ROE auto-QAB with no panel, successful sac (bunted out/GO with runners on) auto-QAB and opens the panel only for optional RBI(squeeze)/moved-runner plus a 'Sac ✓' toggle that undoes a wrongly-assumed sac (runner held), and bunt FC/PO/GDP/K or a bases-empty bunt out = not a QAB with no panel; Hard Hit is never offered or applied on a bunt-flagged pitch (the live HH prompt is suppressed for all bunt results); Sac Fly panel unchanged since deep sac flies can legitimately be hard hit; also fixes buildAtBats dropping at-bats that end in a fielder's choice (fc added to the FINAL set — FC at-bats now appear in the Hitting chart as PAs, non-QAB unless tagged)
// v112  Runner-advancement fixes (live + resume kept identical): a TRIPLE now leaves the batter standing on 3rd (was clearing the bases like a HR — the comment said the right thing, the code didn't); GDP now erases the runner forced at 2nd plus the batter (classic 6-4-3) instead of the lead runner, lead-runner fallback only when 1st is empty, other runners hold; resume-after-FC now mirrors the live lead-runner-out logic (it was instead advancing every runner, so reopening a game after an FC restored different bases than the live chart had shown)
// v113  Test-pass fixes: Elite sync now propagates GAME DELETIONS to other devices (snapshot removals applied locally) and a cloud copy with an updatedAt stamp now beats an unstamped legacy local copy (pitch deletions no longer resurrect); scouting notes + Settings prefs now SYNC across devices via a users/{uid} meta doc with last-write-wins timestamps (fbSaveMeta + meta listener); IBB moved from the result buttons to the Events row — logs an event (no pitch), forced runners advance, count resets, next batter (legacy ibb-result pitches still parse); sac bunt auto-tag now requires 0 OUTS (a bunted out at 1-2 outs = failed bunt for a hit, no QAB, no panel) and a squeeze auto-tags the RBI — sac panel reduced to Sac/RBI confirm-undo chips; SW + registration made path-agnostic (relative register('sw.js'), BASE-derived precache + offline fallback w/ ignoreSearch) so offline works on the dummy site and phone PWAs regardless of hosting path
// v114  Retest fixes: a synced pitch DELETION now refreshes the receiving device's live count/runners/prediction, not just the pitch list — chart state re-derives whenever the cloud copy wins the merge and the pitch count differs in either direction (same updatedAt winner rule as the data merge, so a stale cloud echo can never rewind a device mid-charting); bunted-out runner advancement decoupled from the QAB gate — runners now physically move up on ANY bunted out with runners on (e.g. 1-out bunt-over leaves R2 with 2 outs) while the sacBunt/QAB tag still requires 0 outs, and the resume mirror matches (any bunt-flagged out with runners on advances them, tagged or not)
// v115  License enforcement LIVE: LIC_API set to https://armsight-license.coach-f4f.workers.dev — unlock now rejects keys the sheet says were never issued, every unlocked install rechecks at most every 12h with the server tier authoritative; offline or worker trouble still NEVER locks (grace) — only an affirmative not-issued response does; verified pre-flip: fake key returns valid:false, real keys return correct tiers, sheet column F confirmed as the source of truth
// v116  Data export/backup for ALL tiers (the fix for 'cleared my cache, lost everything' on Pro/Basic): per-game Export (↑) button on every game row writes armsight-{opp}-{date}.json; Settings → Data & Backup adds Export-all-data and Restore-from-backup (restore merges by game id, never deletes, and re-pushes to cloud for Elite); a warning banner shows on the Games tab for any non-cloud-synced user once they have games, pointing them to back up; restore accepts both whole-backup and single-game export files. Export is intentionally all-tier — the tiers most at risk of local data loss are the ones that must be able to back up. Files only, no server/worker involved
// v117  Display fix: the v116 backup banner/buttons were written with literal \uXXXX escapes sitting in raw JSX text, which React renders verbatim — so the warning symbol, the up/down export arrows and the Settings→ arrow showed as the text '\u26A0' etc. instead of ⚠ ↑ ↓ →. Replaced with the real characters (raw JSX text doesn't interpret backslash-u, unlike a quoted string). Also fixed the same pre-existing leak in the Log Hitting popup header (⚾ / —). No logic change
// v118  Charting polish from demo testing: (#1) custom pitches CT/FC/FS/KN/EP/FF/FT/ST/SV now have proper button colors and SI recolored off pure red; auto-generated colors for any other custom pitch use higher lightness so a faint-background button is never red-text-on-red / unreadable. (#2) GDP result button is now white like the other results (was gold). (#4) a Groundout (GO) is now a productive out — every runner advances one base (R1→2, R2→3, R3 scores), batter out; air outs FO/PO/LO still hold runners; QAB auto-awarded by rule: 0 outs + any runner advanced, or 1 out + a run scored (R3 home); 2 outs never; resume mirror matches
// v119  Custom-pitch readability, full fix: a SELECTED pitch button filled its background with the pitch color but always used black text — so a custom pitch (e.g. a breaking ball) whose auto color is dark washed the initials out (bright/unreadable box). New gPCtext() picks black or white text from the actual perceived luminance of the pitch color (handles both hsl and hex), applied to the selected button; auto-generated pitch lightness retuned to 58% so neither the faint-bg (unselected) nor solid-bg (selected) state can blow out the initials
// v120  Real cause of the unreadable custom-pitch button found: a global button:hover{filter:brightness(1.15)} rule — on a touch device (tablet/phone) the :hover state STICKS after a tap, so a pitch button kept the brightness wash after being clicked and its faint initials blew out (looked like a solid color box). Hover brightness is now wrapped in @media(hover:hover) so it only applies to mouse devices and never sticks on touch; added -webkit-tap-highlight-color:transparent. Applies to both the head <style> and the in-app <style>
// v121  GO tag-panel cleanup: a groundout's QAB status is already auto-decided by the v118 rule, so the panel no longer shows a manual QAB toggle for GO (which was redundant and implied QAB was undecided). The GO panel now offers ONLY Hard Hit, with a heading that states the auto status ('Groundout — QAB ✓ · mark hard hit?' or 'Groundout — not a QAB · hard hit?'); tagging Hard Hit on a non-QAB groundout correctly promotes it to a QAB via isQAB. Confirmed no double-counting anywhere: QAB is DERIVED per at-bat (isQAB returns one bool), never summed across tags — a hard-hit + advanced-runner at-bat counts as exactly one QAB
// v122  Ordering bug fix — the real reason runner-advancing groundouts showed as NOT a QAB: p.atBatTags was assigned BEFORE the GO/result branches computed the tags, so the auto advRunner/rbi tag was calculated and then thrown away (never attached to the saved pitch). Moved tag attachment to just before save, after the branches run. Now a GO with R1 at 0 outs (R1→2B) and a GO with R2 at 0 outs (R2→3B) correctly persist advRunner and read as QAB; 1-out GO that scores R3 persists rbi; 2-out GO still none. Affected every auto-tagged result, not just GO
// v123  THE actual reason runner-advancing groundouts read 'not a QAB' on the Hitting tab: the Hitting log kept its own local `tags` state seeded once at mount, and its QAB calc IGNORED the tags stored on the pitch (autoQAB even stripped them). A GO logged after the log mounted had advRunner on the pitch but not in the local map, so it never counted. Hitting tab now derives QAB from effTags = the pitch's stored atBatTags merged with any live local toggles; per-row tag buttons + hard-hit count + auto/manual label all use effTags; toggleTag seeds from stored tags so toggling an auto-on tag works. GO QAB (R1→2B / R2→3B at 0 outs, R3 scoring at 1 out) now registers on the Hitting tab
// v124  THE bug, finally: in logPitch the pitch was attached-and-SAVED (onUpdate) at the TOP, but the GO/result branches that set the advRunner/rbi tag run BELOW that — so the tag was computed into a local var after the pitch had already been saved without it. Earlier 'fixes' moved the attach line but left onUpdate above the branches. Reordered so tag-attach + onUpdate run AFTER every result branch. Now a freshly logged GO (R1@0out, R2@0out, R3@1out scoring) saves with the tag and reads QAB. Also re-added backfillGOTags() in loadData (lost to a sandbox reset on the prior bump) to fix groundouts in games charted before this existed. Net: both new and old groundouts now show QAB correctly
// v125  Name/key editing — new '✎ Edit' button on the chart screen opens an Edit Names panel: rename the starter and any reliever (handedness too), edit any custom pitch KEY, and rename any lineup/hitter slot (incl. pinch hitters). Critically, renaming a pitcher rewrites game.pitcher/the reliever entry AND every p.pitcher reference on already-logged pitches (and curP) so stats don't split across the typo and the fix; renaming a pitch key rewrites pitchTypes AND every p.type reference; lineup names update by slot (pitches key off slot number, no rewrite needed). Fields commit on blur. Scouting notes already had inline edit/delete in the Notes tab, so they're covered there
// v126  Display fix: the v125 Edit button and Edit-panel header used a literal \u270e escape in raw JSX text (renders verbatim, same class as the v117 banner bug), so they showed '\u270e Edit' instead of the ✎ pencil. Replaced with the real character in both spots; scanned the rest of the JSX for other raw-text \uXXXX leaks — none remain. No logic change
// v127  Dropped-3rd-strike (#3): logging K/Kc when the pitch is in the DIRT at 2 strikes AND (2 outs OR 1st base open) — the only situations the batter can run — now pops a follow-up: Out (normal strikeout, unchanged) or Reached 1st. 'Reached' records the K for the pitcher (counts in K/whiff stats, ends the at-bat) but adds NO out and does not flip the inning; batter goes to 1st with forced runners pushed, and the coach taps extra bases for any runner who took more (e.g. the 2-out K-in-dirt-WP-two-runs-score play). Mirrors the existing WP/PB ball-or-strike follow-up; resume state (deriveStateFromGame) honors dropReached so reopening the game restores no-out/runner-on-1st correctly. Solves the manual out-subtraction workaround from demo testing
// v128  Display fix: the v127 dropped-3rd-strike prompt had literal \u2014 and \u201c/\u201d escapes in raw JSX text, so the header and helper line showed '\u2014' / '\u201c' instead of the em-dash and curly quotes. Replaced with real characters; re-scanned all JSX for raw-text \uXXXX leaks — none remain. No logic change
// v129  Times-through-order is now derived PER PITCHER (#5): curPitcherTTO counts only the current pitcher's own faced batters (distinct inning+slot / 9), so a reliever entering starts at 1st-time-through instead of inheriting the starter's count — fixes the TTO shift firing after a reliever's 3rd batter and corrects the TTO stamped on every pitch + fed to the prediction read. The TTO selector is now an auto-tracked read-only display. Shift monitoring continues PAST 2nd time through: each later cycle (2nd, 3rd, 4th…) is compared against the 1st separately and labeled ('SL up 3rd time through 8%→34%'), so a pitch shelved 2nd time but re-introduced 3rd time is surfaced instead of being averaged away in a lumped 'late' bucket. Resets cleanly for each reliever.
// v130  TTO shift detection split into two distinct signals because a re-introduced pitch wasn't being flagged — it only competed (and lost) for the single 'usage up vs 1st time' slot. (A) keeps usage-up: a pitch leaned on >=3x more in a later cycle vs the 1st. (B) NEW shelved-then-back: a pitch established early (>=15% in some cycle), dropped to ~none (<5%) in a later cycle, then re-introduced (>=12%) in an even later cycle — detected by comparing consecutive cycles at lower volume gates so it catches the 'CB shelved 2nd, back 3rd' case the user hit. Up to two TTO tips can now surface together instead of one crowding out the other; labels read e.g. 'CB back 3rd time through (shelved 2nd)'.
// v131  The Pitching-Tendencies 'TTO Pattern Shift' card (a SEPARATE analyzer from the in-game scouting tips fixed in v130) still lumped 2nd+3rd+ into one 'TTO 2+' bucket — so a CB going 55% (1st) -> 0% (2nd) -> 100% (3rd) was hidden and the card misreported 'SL up 0->40, FB down 45->20' off the blended bucket. Rebuilt to read the per-cycle %s the card already displays: detects shelved-then-back (CB ↻ back 3rd time, shelved 2nd), steady climbs (up X->Y by Nth time) and late drops (down X->Y), sorted by swing size, up to 3 shown. No more cross-cycle blending.
// v132  Lossless CSV export/import: per-game 'CSV' button on each game row + 'Export all games as CSV' in Settings write a spreadsheet-friendly file with every field; nested data is encoded into flat columns (runners->"123", tags->"advRunner|hardHit", plus batOrder/timesThrough/hitBases/bunt/dropReached). parsePitchCSV extended to decode those columns back AND read game/date/pitcher meta, so a CSV round-trips with full fidelity (QAB tags, baserunners, batting order, TTO all restored) — matching the JSON path but readable in Excel. Import CSV re-enabled on the Games list (builds pitchTypes from keys present + a lineup from batOrder/batSide; Elite pushes the imported game to cloud). Older simple CSVs (just type/result/etc.) still import as before.
// v133  Team roster + lineup picker + switch hitters. Roster lives at the data root (data.roster: {id,num,name,bats:R/L/B}), persisted, synced for Elite, in backups. Settings -> Manage Team Roster adds/edits players once. New Game lineup now PICKS from the roster (dropdown per slot) instead of retyping, with R/L/B buttons; relabeled 'Your Batting Order' (the hitters are your team, charting the opposing pitcher). Switch hitters (B) auto-bat opposite the CURRENT pitcher via effectiveSide() — RHP faced -> bats L, LHP -> bats R — and flip automatically when a reliever of the other hand enters (getLineupHand re-resolves on pitcher change). B never lands on a pitch: every pitch records the concrete L/R side actually batted from, so the existing per-hitter heat maps (hard-hit-by-zone + Whiff/Chase/Take discipline) already split a switch hitter into clean 'RHB (n)' and 'LHB (n)' panels with no blending. Hand-typed lineups from older games still work unchanged.
// v134  Roster-panel UX from testing: Save button no longer hidden behind the top tab bar (modal clears the bar, sticky header with Save+Close, plus a bottom Save Roster button); clicking outside the roster modal no longer closes it and wipes entries (closes only via Save/Close); Edit-Names pitch-KEY input now white-on-dark with a colored border so initials stay readable for any custom pitch color. The delete-X was already fixed in v133 (still seeing the escape = pre-v133 cache).
// v135  Chart header tweaks: the game's total pitch count now sits in parens directly next to the current pitcher's count (e.g. '42p (87 total)'); the current batter now shows their JERSEY number from the team roster ('#24 Smith') instead of the lineup-spot number. Jersey is stored on the lineup slot when picked from the roster and also resolved live via rosterId/name, so existing lineups show it too (roster passed into ChartGame).
// v136  Chart header: the current pitcher's pitch count moved next to his name as a separated pill ('P: Smith (RHP) [12 pitches]') so it reads as its own stat, not part of his name; removed the game-total count from the header (available in the Pitching Tendencies tab). Current batter (#jersey name) stays on the right.

// Everything the app needs to run completely offline
// App-shell paths derived from wherever this SW is served (path-agnostic — works on the dummy site)
const BASE = new URL('./', self.location).pathname;

const PRECACHE = [
  BASE,
  BASE + 'index.html',
  'https://fonts.googleapis.com/css2?family=Anybody:wght@400;500;600;700;800&family=Azeret+Mono:wght@400;500;700&display=swap',
  'https://cdnjs.cloudflare.com/ajax/libs/react/18.2.0/umd/react.production.min.js',
  'https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.2.0/umd/react-dom.production.min.js',
  'https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/7.23.9/babel.min.js',
  // Firebase SDK — cached so cloud sync works on a cold offline start (Firestore queues offline writes, flushes on reconnect)
  'https://www.gstatic.com/firebasejs/9.23.0/firebase-app-compat.js',
  'https://www.gstatic.com/firebasejs/9.23.0/firebase-auth-compat.js',
  'https://www.gstatic.com/firebasejs/9.23.0/firebase-firestore-compat.js',
];

// Hosts whose responses may be runtime-cached (never API traffic like Firestore channels)
const RUNTIME_HOSTS = new Set(['fonts.googleapis.com', 'fonts.gstatic.com', 'cdnjs.cloudflare.com', 'www.gstatic.com']);

// Install — cache everything up front on first visit
self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE).then(cache => {
      // App shell must cache or install fails (old cache stays live); CDN files are best-effort
      const critical = PRECACHE.filter(u => u.startsWith('/'));
      const extras = PRECACHE.filter(u => !u.startsWith('/'));
      return cache.addAll(critical).then(() => Promise.allSettled(
        extras.map(url =>
          cache.add(url).catch(err => {
            console.warn('[SW] Failed to cache:', url, err);
          })
        )
      ));
    })
    // No skipWaiting() here — the new SW waits so the in-page update banner
    // can offer the update; the banner sends SKIP_WAITING to activate it.
  );
});

// Activate — remove old caches
self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys.filter(k => k !== CACHE).map(k => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  );
});

// Fetch — serve from cache first, fall back to network
self.addEventListener('fetch', event => {
  // Only handle GET requests
  if (event.request.method !== 'GET') return;

  event.respondWith(
    caches.match(event.request).then(cached => {
      if (cached) return cached;
      // Not in cache — try network and cache the response
      return fetch(event.request).then(response => {
        if (!response || response.status !== 200) return response;
        let host = '';
        try { host = new URL(event.request.url).hostname; } catch (e) {}
        if (event.request.url.startsWith(self.location.origin) || RUNTIME_HOSTS.has(host)) {
          const clone = response.clone();
          caches.open(CACHE).then(cache => cache.put(event.request, clone));
        }
        return response;
      }).catch(() => {
        // Offline and not cached — for navigation requests return app shell
        if (event.request.mode === 'navigate') {
          return caches.match(BASE + 'index.html', { ignoreSearch: true });
        }
      });
    })
  );
});

// Message listener — page can send SKIP_WAITING to activate new SW immediately
self.addEventListener('message', event => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
